apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://k8s:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: jenkins-robot
  name: default
current-context: default
users:
- name: jenkins-robot
  user:
    token: <PUT_YOUR_TOKEN_HERE>
